/** Vietnamese banks list — sourced from NAPAS/SBV */
export interface VietnamBank {
    code: string;
    name: string;
    shortName: string;
}

export const VIETNAM_BANKS: VietnamBank[] = [
    { code: "VCB", name: "Ngân hàng TMCP Ngoại Thương Việt Nam", shortName: "Vietcombank" },
    { code: "BIDV", name: "Ngân hàng TMCP Đầu Tư và Phát Triển Việt Nam", shortName: "BIDV" },
    { code: "VTB", name: "Ngân hàng TMCP Công Thương Việt Nam", shortName: "VietinBank" },
    { code: "AGR", name: "Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam", shortName: "Agribank" },
    { code: "TCB", name: "Ngân hàng TMCP Kỹ Thương Việt Nam", shortName: "Techcombank" },
    { code: "MBB", name: "Ngân hàng TMCP Quân Đội", shortName: "MB Bank" },
    { code: "ACB", name: "Ngân hàng TMCP Á Châu", shortName: "ACB" },
    { code: "VPB", name: "Ngân hàng TMCP Việt Nam Thịnh Vượng", shortName: "VPBank" },
    { code: "TPB", name: "Ngân hàng TMCP Tiên Phong", shortName: "TPBank" },
    { code: "STB", name: "Ngân hàng TMCP Sài Gòn Thương Tín", shortName: "Sacombank" },
    { code: "HDB", name: "Ngân hàng TMCP Phát Triển TP HCM", shortName: "HDBank" },
    { code: "SHB", name: "Ngân hàng TMCP Sài Gòn - Hà Nội", shortName: "SHB" },
    { code: "VIB", name: "Ngân hàng TMCP Quốc Tế Việt Nam", shortName: "VIB" },
    { code: "SEA", name: "Ngân hàng TMCP Đông Nam Á", shortName: "SeABank" },
    { code: "MSB", name: "Ngân hàng TMCP Hàng Hải Việt Nam", shortName: "MSB" },
    { code: "LPB", name: "Ngân hàng TMCP Bưu Điện Liên Việt", shortName: "LPBank" },
    { code: "OCB", name: "Ngân hàng TMCP Phương Đông", shortName: "OCB" },
    { code: "EIB", name: "Ngân hàng TMCP Xuất Nhập Khẩu Việt Nam", shortName: "Eximbank" },
    { code: "KLB", name: "Ngân hàng TMCP Kiên Long", shortName: "KienlongBank" },
    { code: "NAB", name: "Ngân hàng TMCP Nam Á", shortName: "Nam A Bank" },
    { code: "NCB", name: "Ngân hàng TMCP Quốc Dân", shortName: "NCB" },
    { code: "PGB", name: "Ngân hàng TMCP Xăng Dầu Petrolimex", shortName: "PGBank" },
    { code: "SCB", name: "Ngân hàng TMCP Sài Gòn", shortName: "SCB" },
    { code: "ABB", name: "Ngân hàng TMCP An Bình", shortName: "ABBank" },
    { code: "BAB", name: "Ngân hàng TMCP Bắc Á", shortName: "BacABank" },
    { code: "BVB", name: "Ngân hàng TMCP Bảo Việt", shortName: "BaoVietBank" },
    { code: "CBB", name: "Ngân hàng Xây Dựng Việt Nam", shortName: "CBBank" },
    { code: "SAIGON", name: "Ngân hàng TMCP Sài Gòn Công Thương", shortName: "SaigonBank" },
    { code: "VAB", name: "Ngân hàng TMCP Việt Á", shortName: "VietABank" },
    { code: "VBB", name: "Ngân hàng TMCP Việt Nam Thương Tín", shortName: "VietBank" },
    { code: "CAKE", name: "Ngân hàng số Cake by VPBank", shortName: "CAKE" },
    { code: "UBANK", name: "Ngân hàng số Ubank by VPBank", shortName: "Ubank" },
    { code: "TIMO", name: "Ngân hàng số Timo by BanViet", shortName: "Timo" },
    { code: "VBSP", name: "Ngân hàng Chính Sách Xã Hội", shortName: "VBSP" },
    { code: "VDB", name: "Ngân hàng Phát Triển Việt Nam", shortName: "VDB" },
    { code: "CIMB", name: "Ngân hàng CIMB Việt Nam", shortName: "CIMB" },
    { code: "WOO", name: "Ngân hàng Woori Việt Nam", shortName: "Woori" },
    { code: "UOB", name: "Ngân hàng UOB Việt Nam", shortName: "UOB" },
    { code: "SCBVN", name: "Ngân hàng Standard Chartered Việt Nam", shortName: "Standard Chartered" },
    { code: "HSBC", name: "Ngân hàng HSBC Việt Nam", shortName: "HSBC" },
    { code: "SHBVN", name: "Ngân hàng Shinhan Việt Nam", shortName: "Shinhan Bank" },
];
